#!/bin/sh                                                                                                                                                                                                                                     
set -u                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                              
argument="$1"                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                              
PWMCHIP="/sys/class/pwm/pwmchip0"                                                                                                                                                                                                             
PWMCHANNEL0="0"                                                                                                                                                                                                                               
PWMCHANNEL1="1"                                                                                                                                                                                                                               
                                                                                                                                                                                                                                              
activate_channel() {                                                                                                                                                                                                                          
    CHANNEL=$1                                                                                                                                                                                                                                
                                                                                                                                                                                                                                              
    if [ ! -d "$PWMCHIP/$CHANNEL" ]; then                                                                                                                                                                                                     
        echo "$CHANNEL" > "$PWMCHIP/export"                                                                                                                                                                                                   
        sleep 0.1  # short delay to let the system create the directory                                                                                                                                                                       
    fi                                                                                                                                                                                                                                        
}                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
deactivate_channel() {                                                                                                                                                                                                                        
    CHANNEL=$1                                                                                                                                                                                                                                
                                                                                                                                                                                                                                              
    if [ -d "$PWMCHIP/pwm$CHANNEL" ]; then                                                                                                                                                                                                    
        echo "$CHANNEL" > "$PWMCHIP/unexport"                                                                                                                                                                                                 
        sleep 0.1  # short delay to let the system delete the directory                                                                                                                                                                       
    fi                                                                                                                                                                                                                                        
}                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
get_channel_status() {                                                                                                                                                                                                                        
    CHANNEL=$1                                                                                                                                                                                                                                
                                                                                                                                                                                                                                              
    if [ -d "$PWMCHIP/$CHANNEL" ]; then                                                                                                                                                                                                       
        echo "PWM channel $CHANNEL has be exported."                                                                                                                                                                                          
    else                                                                                                                                                                                                                                      
        echo "PWM channel $CHANNEL has NOT be exported."                                                                                                                                                                                      
    fi                                                                                                                                                                                                                                        
}                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
start() {                                                                                                                                                                                                                                     
    activate_channel "$PWMCHANNEL0"                                                                                                                                                                                                           
    activate_channel "$PWMCHANNEL1"                                                                                                                                                                                                           
}                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
stop() {                                                                                                                                                                                                                                      
    deactivate_channel "$PWMCHANNEL0"                                                                                                                                                                                                         
    deactivate_channel "$PWMCHANNEL1"                                                                                                                                                                                                         
}                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
restart() {                                                                                                                                                                                                                                   
    deactivate_channel "$PWMCHANNEL0"                                                                                                                                                                                                         
    deactivate_channel "$PWMCHANNEL1"                                                                                                                                                                                                         
                                                                                                                                                                                                                                              
    activate_channel "$PWMCHANNEL0"                                                                                                                                                                                                           
    activate_channel "$PWMCHANNEL1"                                                                                                                                                                                                           
}                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
status() {                                                                                                                                                                                                                                    
    get_channel_status "$PWMCHANNEL0"                                                                                                                                                                                                         
    get_channel_status "$PWMCHANNEL1"                                                                                                                                                                                                         
}                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
if ! [ $# -eq 1 ]                                                                                                                                                                                                                             
then                                                                                                                                                                                                                                          
    echo "Usage: pwm_init.sh {start|stop|restart|status}"                                                                                                                                                                                     
    exit 1                                                                                                                                                                                                                                    
fi                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
if [ ! -d "$PWMCHIP" ]; then                                                                                                                                                                                                                  
    echo "PWM chip not available. Is the overlay enabled in /boot/config.txt?"                                                                                                                                                                
    exit 1                                                                                                                                                                                                                                    
fi                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                              
case "$argument" in                                                                                                                                                                                                                           
    start)                                                                                                                                                                                                                                    
        start                                                                                                                                                                                                                                 
        ;;                                                                                                                                                                                                                                    
    stop)                                                                                                                                                                                                                                     
        stop                                                                                                                                                                                                                                  
        ;;                                                                                                                                                                                                                                    
    restart)                                                                                                                                                                                                                                  
        restart                                                                                                                                                                                                                               
        ;;                                                                                                                                                                                                                                    
    status)                                                                                                                                                                                                                                   
        status                                                                                                                                                                                                                                
        ;;                                                                                                                                                                                                                                    
    *)                                                                                                                                                                                                                                        
        echo "Usage: pwm_init.sh {start|stop|restart|status}"                                                                                                                                                                                 
        exit 1                                                                                                                                                                                                                                
        ;;                                                                                                                                                                                                                                    
esac